#!/bin/bash

function python_is_python3 {
    source script_msg
    if [[ $(which python | wc -l) -eq 0 ]]; then
        PY=$(which python3)
        DIR=$(dirname $PY)
        ln -s "$PY" "$DIR/python"
        script_msg "Created symlink from $DIR/python to $PY"
    else
        # do nothing
        :  
    fi 
}